### ISSUE TITLE
Add libxlsxwriter topic to the GitHub project metadata

### ISSUE THREAD

**Issue by jmcnamara** [Alexhuszagh/libxlsxwriterpp#2]
Hi Alex,

Could you add `libxlsxwriter` as a "topic" metadata to the project like libxlsxwriter: https://github.com/jmcnamara/libxlsxwriter

Other examples: https://github.com/search?q=topic%3Alibxlsxwriter&type=Repositories

Thanks,

John

**Comment by Alexhuszagh** [comment]
@jmcnamara Done, although I will be making significant changes later this week.
