### ISSUE TITLE
Typo in the build instructions

### ISSUE THREAD

**Issue by jmcnamara** [Alexhuszagh/libxlsxwriterpp#3]
Hi,

The [ReadMe](https://github.com/Alexhuszagh/libxlsxwriterpp/blob/master/README.md) has the following instructions:

```bash
cmake .. -_DBUILD_TESTS=ON
```

I think there is a stray underscore there and it should be:

```bash
cmake .. -DBUILD_TESTS=ON
```
John

**Comment by Alexhuszagh** [comment]
Thank you for spotting this, and patched.
